travis:
  secure:
    BINSTAR_TOKEN: w00Min56zI94GLrUvN1d5w+WqUaS16DaKCbfbuSwbxq2/0my4A7v189syGeuPDp7+wwc7meETYNIrJkf7dZnQWY4cwn90fEgxeZeL3UWS6qvt8MERvaiLc7XkExDvo9c9rRX8C7grwG76qYBkrEmfC64lkEqTqhpb7hDRl0x863mUB3jLtwqKS5eIDOfiKveJtH7E+0OAaMag2BHjDkxVAEnxoJQNgPcna/RQXAOPgZWGSDJqXQ4xbMeWGjl5A46LJGt6fsMp5fvvOhDWcjUu/zG1HQDxrJtbjnlT7bMT/O9vf3tqH8izrtfUU54FJaEVKu8SnnX1kgVjqj3ammP9vAzityYIaCHFirZoZzYaKP8btiwb4xrgAUMiJ5wXkXrp03UNGrUXAngpxlRzBTUCZV863IJkGtbQ1gm8echVe7Ii8XfY5y4dvcT8oIIoBUw/OyR68P6XB0DMuhExNM/IThAFObe/7Ywi0PzOzykWalGGeLaSLnCC+ocBmCLq7EzIaVyhNPAcJbw1wAIlP6jX+EoVqh1JmuT6xYcBC0jDOnR+lp4CyNWRXv9zrTws6M4Idt9C3BQXlxJyy3qi0XE9JK7z/7sWjt2UjqsyhByyytJJQxomgDAQfxAvqTBhv9MpB71xEXGJZj+DM4X+hbG4A2/LU5XrH16kwqFgoqIAuc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
